name: minetest
summary: "Minetest"
description: |
  Minetest is a minecraft-inspired game written from scratch and licensed
  under the LGPL (version 2.1 or later). It supports both survival and
  creative modes along with multiplayer support, dynamic lighting, and an
  "infinite" map generator.
grade: stable
confinement: strict
icon: snap/gui/minetest.svg
adopt-info: minetest
base: core18
compression: lzo

architectures:
  - build-on: armhf
  - build-on: i386
  - build-on: amd64

apps:
  minetest:
    environment:
      HOME: "$SNAP_USER_COMMON"
    command: launcher
    plugs: [desktop, desktop-legacy, x11, network, network-bind, opengl, audio-playback, home, removable-media]

parts:
  launcher:
    source: snap/scripts
    plugin: dump
  minetestgame:
    source: https://github.com/minetest/minetest_game.git
    plugin: dump
    override-pull: |
      snapcraftctl pull
      last_committed_tag="$(git for-each-ref --sort=taggerdate --format '%(tag)' refs/tags | tail -n 1)"
      last_released_tag="$(snap info minetest | awk '$1 == "latest/beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
      fi 
    override-build: |
      snapcraftctl build
    organize:
      '*': 'share/minetest/games/minetest_game/'
  minetest:
    source: https://github.com/minetest/minetest.git
    override-pull: |
      snapcraftctl pull
      last_committed_tag="$(git for-each-ref --sort=taggerdate --format '%(tag)' refs/tags | tail -n 1)"
      last_released_tag="$(snap info minetest | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
        # Needed  by the cmake plugin
        cd ../src
        git checkout "${last_committed_tag}"
      fi
      snapcraftctl set-version "$(git describe --tags)"
    override-build: |
      snapcraftctl build
    plugin: cmake
    configflags: ["-DRUN_IN_PLACE=FALSE", "-DCMAKE_BUILD_TYPE=Release"]
    build-packages:
      - cmake
      - gcc
      - g++
      - gettext
      - imagemagick
      - libbz2-dev
      - libcurl4-gnutls-dev
      - libfreetype6-dev
      - libglu1-mesa-dev
      - libirrlicht-dev
      - libjpeg-dev
      - libjsoncpp-dev
      - libleveldb-dev
      - libluajit-5.1-dev
      - libogg-dev
      - libopenal-dev
      - libpng-dev
      - libpulse-dev
      - libsqlite3-dev
      - libvorbis-dev
      - libx11-dev
      - zlib1g-dev
    stage-packages:
      - libgl1-mesa-dri
      - libpulse0
      - libcurl3-gnutls
      - libgl1-mesa-glx
      - libxshmfence1
      - libxcb-sync1
      - libxcb-present0
      - libxcb-glx0
      - libxcb-dri3-0
      - libxcb-dri2-0
      - libvorbisfile3
      - libsnappy1v5
      - libopenal1
      - libluajit-5.1-2
      - libleveldb1v5
      - libjpeg-turbo8
      - libxxf86vm1
      - libxfixes3
      - libxext6
      - libxdamage1
      - libx11-6
      - libx11-xcb1
      - libfreetype6
      - libirrlicht1.8
      - libpng16-16
